### ISSUE TITLE
Effect on simulation while taking one population as an outgroup, i.e. ((A,B),(C,O))

### ISSUE THREAD

**Issue by BioInf2305** [mmatschiner/F4#1]
First of all thank you very much for this tool which is easy to use and also provide direct interpretation of the results.

However, I have a question concerning the effect of including the outgroup in F4-statistics on the simulation parameters implemented in F4 tool. For instance, if instead of "D", i.e. sister clade of the population "C", I use "O"- a divergent group. How the simulation process will work? Is it correct to use this topology as well in F4 tool? Does, the demographic model implemented in F4, inherently assume that "C" and "D" should be sister clades?

**Comment by mmatschiner** [comment]
Hi, this test assumes an unrooted phylogeny, therefore it does not matter if D is the sister to C or the outgroup, as long as A and B are sisters. Thus, whether the topology can be either ((A,B),(C,D)) or (((A,B),C),D). The simulations will be done as if the topology was ((A,B),(C,D)), but the result would be identical to what you would get with (((A,B),C),D) except that the direction of the substitutions on the branch leading to D would be reversed. This polarization is irrelevant for the test.

**Comment by BioInf2305** [comment]
Thank you very much for the quick and clear response. I understood it now.
